PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

construct {
  ?p1 rdfs:domain owl:Thing.
}
where {
  ?p1 a owl:DatatypeProperty.
  ?p1 rdfs:domain ?d1.
  ?p1 rdfs:domain ?d2.

  filter (!isblank(?p1))
  filter (?d1 != ?d2)
}
