PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

construct {
  ?property rdfs:range ?r2.
}
where {
  ?property a ?propertyType.
  filter (?propertyType in (owl:AnnotationProperty, owl:DatatypeProperty, owl:ObjectProperty))

  ?property rdfs:range ?r1.
  ?property rdfs:range ?r2.

  filter (!isblank(?property))
  filter (!isblank(?r1))
  filter (!isblank(?r2))
  filter (?r1 != ?r2)

  ?r1 rdfs:subClassOf ?r2.
}
