PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

insert {
  ?class rdfs:subClassOf [
    a owl:Restriction;
    owl:maxCardinality ?cardinality;
    owl:onProperty ?property
  ].
  ?class rdfs:subClassOf [
      a owl:Restriction;
      owl:onProperty ?property;
      owl:allValuesFrom ?onClass, ?onDataRange;
  ]
}
where {
  ?class rdfs:subClassOf ?restriction.
  ?restriction a owl:Restriction.
  ?restriction owl:maxQualifiedCardinality ?cardinality.
  ?restriction owl:onProperty ?property.
  OPTIONAL {
    ?restriction owl:onDataRange ?onDataRange.
  }
  OPTIONAL {
    ?restriction owl:onClass ?onClass.
  }
}
